---
title: "r_for_newbies"
author: "Edward Palmer"
date: "15/11/2016"
output: beamer_presentation
font-family: "helvetica"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Learning Objectives 

- Discover what R is
- Understand the advantages of R
- Find your way around RStudio
- Get to know the basic R building blocks
- Get your hands dirty in R

## What is R?

- R is a free software environment for statistical computing and graphics
- It works with a wide variety of platforms

## Why R?

1. You can do **anything** in R.
2. R facilitates reproducible science
3. Long term gain from upfront investment

## RStudio - Making R a Breeze

- RStudio helps you write in R by:
    + sending your written code to R
    + 'syntax-highlighting'
    + keeping a history of your actions
    + giving you tools to fix your code when it doesn't work (debugging)
    
## RStudio - A visual walkthrough

- Livecoding session
    + RStudio planes
    + Navigating directory structure
- There's a handy cheat sheet for R studio available: (https://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf). 
- Exercise: Set your working directory to your new project folder

## R building blocks

- The 3 main building block of R are:
    + names
    + data: vectors and data frames
    + functions

## Names

- We use the `<- ` assignment operator to assign a name. 

## Data

- Vectors
- Dataframes

## Functions

- Functions are litte machines that perform specific tasks.