---
layout: lesson
author: "Danny Wong"
root: .
title: Data pipelines
minutes: 25
---

<!-- rename file with the lesson name replacing template -->

## Learning Objectives 

1. [Load in your own data](#load)
2. [Examine your data in general](#examine)
3. [Explore individual variables](#exploration)
4. [Think of some questions/hypotheses](#hypotheses)
5. [Do some bivariate plots](#bivariate)
6. [Think of constructing a model](#model)

<!-- * Data Analysis Practical Worksheet - (v1) Danny

- [ ] Decide on the structure for analysis
- [ ] Create a example analysis for the Outreach dataset

 -->

## Lesson 

This lesson will be a guided practical applying all the principles learned over the course.

You may have some of your own data that you would like to analyse, using this worksheet as a guide. Alternatively you can use the datasets we have been interacting with during the course.

- An [RCT]({{page.dataurl_2%}}) comparing post-operative pain control after axillary node dissection with local anaesthetic infiltration via the drain versus injection to the skin flaps (Thanks to Muska Khpal)
- [SPOTlight study data]({{page.dataurl_1 %}}): an observational study of deteriorating ward patients referred to critical care

<a name="load"></a>

### Step 1: Load in your own data

Depending on the form your data takes, use `read.csv()`, `read.table()` or `readxl::read_excel()` to bring your data in to `R`, and assign it to an object name.

```
# For example
dataframe.name <- read.csv("file/path.csv", ...)

# If using an .xlsx file
library(readxl)
dataframe.name <- read_excel("file/path.xlsx", ...)
```

<a name="examine"></a>

### Step 2: Examine your data in general

You want some idea of what your data looks like, so you can have a feel of what you have to play with. Try answering the following questions about your own dataset to make sure you understand it:

- Did the dataset load correctly into R? Remember sometimes there are weird column names
- Do you have a lot of empty cells that got loaded at the bottom of the dataframe which are actually useless?
- Do you know how many observations your dataset has or should have?
- What variables do you have in your dataset?

```
# Try using some of the following commands
View(dataframe.name)
head(dataframe.name)
tail(dataframe.name)
summary(dataframe.name)
nrow(dataframe.name)
str(dataframe.name)
names(iris)

# Try using this function from the Hmisc package
# You might need to first install the package
# install.packages("Hmisc")
library(Hmisc)
describe(dataframe.name)
```
<a name="exploration"></a>

### Step 3: Explore individual variables

Now that you have had a general look at the data overall, try to zoom in on particular variables of interest. At this point you might start to have questions of the data that might start forming in your mind:

- Pick a few variables.
- What data types are these? E.g. integer/numeric, text strings, categorical/factors, binary? Are they correctly listed or do they need changing? You may have already taken note of this in the previous step.
- Assess the distribution of the data variables, are they normally distributed or skewed? Are there any visible outliers?
- For categorical variables, do you have any idea what the frequencies/proportions are for each category?
- Are there a significant number of missing recordings in your variables?

```
# For large dataframes with many columns, it may sometimes be useful to pick out a few of the variables you are interested in using select from the dplyr package
library(dplyr)
restricted.dataframe.name <- dataframe.name %>% select(variable1, variable2, variable3, ...)

# Alternatively you could use base R
restricted.dataframe.name <- dataframe.name[ , c("variable1", "variable2", "variable3", ...)]

# Now look through each variable, if you haven't already, try:
str(restricted.dataframe.name)

# Plot some histograms
hist(restricted.dataframe.name$variable1)

# Or the ggplot2 way
library(ggplot2)
ggplot(restricted.dataframe.name, aes(variable1)) + geom_histogram()

# Categorical variables can be viewed using tables
table(restricted.dataframe.name$categorical.variable) # gives absolute counts
table.name <- table(restricted.dataframe.name$categorical.variable)
prop.table(table.name) # gives proportions

# Use the is.na() function for looking at missingness
table(is.na(dataframe.name$variable2))
```

---

[Previous topic](06-lesson-06-dataviz.html)
